# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: gtri.fhir.cbs
canonical: http://cbsig.chai.gatech.edu
name: CBSIG
title: "Case Based Surveillance Implementation Guide"
description: An IG that is used to support case based surveillance messaging for the public health domain
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
dependencies: 
  us.cdc.phinvads:
    uri: http://fhir.org/packages/us.cdc.phinvads
    version: 0.7.0
  hl7.fhir.us.core:
    version: 4.0.0
  hl7.fhir.us.ecr:
    version: 1.0.0



# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: 
    Profiles: artifacts.html#1
    Extensions: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4
  Examples: examples.html
