# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: gtri.fhir.cbs
canonical: http://cbsig.chai.gatech.edu
name: CBSIG
title: "Case Based Surveillance Implementation Guide"
description: An IG that is used to support case based surveillance messaging for the public health domain
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build
publisher:
  name: Georgia Tech Research Institute (GTRI)
  url: http://gtri.gatech.edu/
dependencies:
  us.cdc.phinvads:
    uri: http://fhir.org/packages/us.cdc.phinvads
    version: 0.7.0
  hl7.fhir.us.core:
    version: 4.0.0
  hl7.fhir.us.ecr:
    version: 2.0.0
  hl7.fhir.us.odh:
    version: 1.1.0
groups:
  CBSProfiles:
    name: CBS Profiles
    description: Case Based Surveillance Profiles
    resources:
    - StructureDefinition/cbs-cause-of-death
    - StructureDefinition/cbs-composition
    - StructureDefinition/cbs-document-bundle
    - StructureDefinition/cbs-questionnaire
    - StructureDefinition/cbs-reporting-source-organization
    - StructureDefinition/cbs-social-determinants-of-health
    - StructureDefinition/cbs-specimen
    - StructureDefinition/cbs-vaccination-ACIP-Recommendation
  CBSCNPProfiles:
    name: CBS CNP Profiles
    description: Case Based Surveillance Case Notification Panel Profiles
    resources:
    - StructureDefinition/cbs-case-notification-panel
    - StructureDefinition/cbs-exposure-observation
    - StructureDefinition/cbs-mmwr
    - StructureDefinition/cbs-age-at-investigation
    - StructureDefinition/cbs-binational-reporting-criteria
    - StructureDefinition/cbs-investigation-start-date
    - StructureDefinition/cbs-case-outbreak
    - StructureDefinition/cbs-date-initial-report
    - StructureDefinition/cbs-date-reported-to-phd
    - StructureDefinition/cbs-earliest-date-reported-to-county
    - StructureDefinition/cbs-earliest-date-reported-to-state
    - StructureDefinition/cbs-immediate-nnc
    - StructureDefinition/cbs-jurisdiction-code
    - StructureDefinition/cbs-national-reporting-jurisdiction
    - StructureDefinition/cbs-pregnancy-status
    - StructureDefinition/cbs-reporting-county
    - StructureDefinition/cbs-reporting-state
    - StructureDefinition/cbs-transmission-mode
  USCBSProfiles:
    name: US CBS Profiles
    description: United States Case Based Surveillance Profiles
    resources:
    - StructureDefinition/us-cbs-condition
    - StructureDefinition/us-cbs-hospitalization
    - StructureDefinition/us-cbs-immunization
    - StructureDefinition/us-cbs-lab-diagnosticreport
    - StructureDefinition/us-cbs-lab-observation
    - StructureDefinition/us-cbs-patient
    - StructureDefinition/us-cbs-performing-lab
    - StructureDefinition/us-cbs-travel-history
  CBSExtensions:
    name: CBS Extensions
    description: Case Based Surveillance Extensions
    resources:
    - StructureDefinition/cbs-case-class-status
    - StructureDefinition/cbs-cdc-address-use
    - StructureDefinition/cbs-illness-duration
    - StructureDefinition/cbs-related-case
    - StructureDefinition/cbs-specimen-role
  USCBSExtensions:
    name: US CBS Extensions
    description: United States Case Based Surveillance Extensions
    resources:
    - StructureDefinition/us-cbs-period-and-mode-of-travel
    - StructureDefinition/us-cbs-program-specific-time-window
pages:
  index.md:
    title: Home
  general-guidance.md:
  conformance-expectations.md:
  profiles-and-extensions.md:
  terminology.md:
  examples.md:
  mapping.md:
    title: Message Mapping Guide to Case Based Surveillance IG Profile Mapping
  program-questionnaires.md:




# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance: #guidance.html
    General Guidance: general-guidance.html
    Conformance Expectations: conformance-expectations.html
  Artifacts:
    Profiles and Extensions: profiles-and-extensions.html
    Terminology: terminology.html
  Examples:
    GenV2 Test Case 1: examples.html#genv2-test-case-1-hemolytic-uremic-syndrome-hus
    HAICA Test Case 2: examples.html#hai-ca-test-case-2-candida-auris-clinical
    Lyme Test Case: examples.html#lyme-test-case-lyme-disease
    STD Test Case 5: examples.html#std-test-case-5-gonorrhea
  Mapping Guide:
    General Guidance: mapping.html#general-guidance
    GenV2: mapping.html#gen-v2
    Vaccination History (Mumps): mapping.html#mumps-vaccination-history
  Program Questionnaires: program-questionnaires.html
